version: "3.2"

services:
  squadmakers-intern-service:
    image: squadmakers-intern-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8006:80
      - 10009:10009
    environment:
      - DEBUGGER=True
      - WEB_APP_VERSION=0.0.0
      - WEP_APP_TITLE=squadmakers
      - WEP_APP_DESCRIPTION= Service for the manage of the jokes services
      - DATABASE_URL=postgres://postgres:J#h69FLxXxPfyBZ@db.awqhhtkwezimydksqtec.supabase.co:5432/postgres
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_HOST=db.awqhhtkwezimydksqtec.supabase.co
      - POSTGRES_PASSWORD=J#h69FLxXxPfyBZ
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_MINSIZE=1
      - POSTGRES_MAXSIZE=20
    networks:
      - squadmakers

volumes:
  redis_data:
    driver: local

networks:
  squadmakers:
    external: true
